name: front ci

on:
  push:
    branches:
      - main
      - "release-*"
    paths-ignore:
      - "backend/**"
  pull_request:
    branches:
      - main
      - "release-*"
    paths-ignore:
      - "backend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup node LTS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn

      - name: install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
          dir: "site"

      - name: lint
        uses: borales/actions-yarn@v4
        with:
          cmd: lint
          dir: "site"

      - name: build
        uses: borales/actions-yarn@v4
        with:
          cmd: build
          dir: "site"
